package com.bigphil.mergehell.progression;

public enum UpgradeId {
    COMMIT_RICOCHET,
    COMMIT_CRITICAL,
    FORCE_EXTRA_PELLETS,
    FORCE_KNOCKBACK,
    DASH_CACHE,
    SHIELD_REBOOT,
    DRONE_COPILOT,
    COMBO_WINDOW,
    DEPENDENCY_CORE_COMMIT,
    DEPENDENCY_CORE_FORCE,
    RAPID_PIPELINE,
    RAPID_SIGNED_BUILDS,
    GC_COMPACTION,
    GC_GENERATIONS,
    FIREWALL_DENSITY,
    FIREWALL_PRESSURE,
    BEAM_FOCUS,
    BEAM_REFRACTION,
    DEPENDENCY_CORE_RAPID,
    DEPENDENCY_CORE_GC,
    DEPENDENCY_CORE_FIREWALL,
    DEPENDENCY_CORE_BEAM,
    SUPPLY_REPAIR,
    SUPPLY_BOMB,
    SUPPLY_SHIELD
}
