#!/usr/bin/env python3
"""Export inspected, generated chapter 3–5 paintings; preserve original RGB and native alpha."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path
import shutil
from PIL import Image, ImageDraw, ImageFont
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
SOURCES = ROOT / 'docs/design/evolution/sources/chapter-premium'
OUTPUT = ROOT / 'src/main/resources/game/art'
QA = ROOT / 'docs/design/evolution/chapter-art-proof'
NAMES = ('enemy-a', 'enemy-b', 'enemy-c', 'boss-shell', 'boss-limb', 'boss-core')
# These are inspected asset cells, not the requested grid: the generated composition gave bosses
# wider cells. Each cell has transparent gutters, and no opaque connected component is clipped.
CELLS = {
    3: [(0, 0, 554, 470), (554, 0, 1028, 470), (1028, 0, 1536, 470),
        (0, 500, 810, 1024), (810, 470, 1080, 1024), (1080, 470, 1536, 1024)],
    4: [(0, 0, 510, 462), (510, 0, 1108, 462), (1108, 0, 1536, 462),
        (0, 462, 885, 1024), (885, 462, 1182, 1024), (1182, 462, 1536, 1024)],
    5: [(0, 0, 704, 452), (704, 0, 986, 498), (986, 0, 1536, 478),
        (0, 452, 730, 1024), (730, 498, 1120, 1024), (1120, 478, 1536, 1024)],
}
SOCKETS = {
    3: [{'muzzle': (22, 163)}, {'shield': (650, 226)}, {'muzzle': (1040, 282)},
        {'core': (416, 724), 'left-joint': (100, 760), 'right-joint': (705, 760)},
        {'joint': (943, 531)}, {'core': (1295, 751)}],
    4: [{'muzzle': (52, 235)}, {'muzzle': (523, 308)}, {'muzzle': (1115, 272)},
        {'core': (842, 679), 'front-joint': (69, 727)}, {'joint': (1090, 512)},
        {'core': (1350, 755)}],
    5: [{'muzzle': (69, 211)}, {'core': (836, 137)}, {'muzzle': (1009, 332)},
        {'core': (350, 720), 'left-joint': (145, 746), 'right-joint': (605, 746)},
        {'joint': (871, 534), 'core': (980, 731)}, {'core': (1320, 723)}],
}
ACTUAL = {3: [(58,58),(60,78),(54,44),(280,170),(55,80),(64,62)],
          4: [(44,42),(62,42),(68,58),(240,160),(62,92),(54,58)],
          5: [(66,62),(58,72),(70,38),(270,220),(64,84),(80,100)]}

def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()

def metadata(name, frames, layer):
    lines = ['# Generated by scripts/art/export_chapter_art.py; frame-local pixel coordinates.',
             'format=1', f'atlas=game/art/{name}.png', 'pixelsPerUnit=1', f'layer={layer}',
             'default=' + frames[0]['name'], 'clips=' + ','.join(f['name'] for f in frames)]
    for f in frames:
        n = f['name']
        lines += ['', f'clip.{n}.loop=true', f'clip.{n}.frames={n}',
                  f'frame.{n}.rect=' + ','.join(map(str,f['atlas_rect'])),
                  f'frame.{n}.durationMs=1000', f'frame.{n}.anchor=' + ','.join(map(str,f['anchor']))]
        if f.get('sockets'):
            lines.append(f'frame.{n}.sockets=' + ','.join(f['sockets']))
            for socket, xy in f['sockets'].items():
                lines.append(f'frame.{n}.socket.{socket}=' + ','.join(map(str,xy)))
    return '\n'.join(lines) + '\n'

def prepare(source, cell, name, sockets):
    cropped = source.crop(cell)
    a = np.asarray(cropped)[:,:,3]
    # Any real material touching a cell border would be a sliced-off body part.
    assert max(a[0].max(),a[-1].max(),a[:,0].max(),a[:,-1].max()) < 8, (name,cell,'clipped')
    # The generated alpha contains scattered 1/255 noise far outside silhouettes. Use a
    # 3%-coverage boundary for framing only; retain the native RGBA within the selected crop.
    box = cropped.getchannel('A').point(lambda value: 255 if value >= 8 else 0).getbbox()
    assert box is not None
    raw = cropped.crop(box)
    scale = min(1., 640. / max(raw.size))
    size = (round(raw.width*scale),round(raw.height*scale))
    reduced = raw.resize(size, Image.Resampling.LANCZOS) if size != raw.size else raw
    image = Image.new('RGBA', (reduced.width+4,reduced.height+4))
    image.paste(reduced,(2,2))
    transformed = {k: [round((v[0]-cell[0]-box[0])*size[0]/raw.width+2,5),
                       round((v[1]-cell[1]-box[1])*size[1]/raw.height+2,5)] for k,v in sockets.items()}
    alpha = np.asarray(image)[:,:,3]
    assert alpha.min()==0 and alpha.max()>=248
    assert np.count_nonzero(alpha>=248)>1000
    info = {'name':name,'source_cell':cell,'source_crop':[cell[0]+box[0],cell[1]+box[1],cell[0]+box[2],cell[1]+box[3]],
            'native_source_alpha':True,'size':list(image.size),'anchor':[image.width/2.,image.height-2.],
            'sockets':transformed,'source_sockets':sockets,'scale':[size[0]/raw.width,size[1]/raw.height],
            'transparent_pixels':int((alpha==0).sum()), 'high_coverage_pixels':int((alpha>=248).sum()),
            'soft_alpha_pixels':int(((alpha>0)&(alpha<248)).sum()),'alpha_max':int(alpha.max())}
    if name in ('boss-limb','boss-core'): info['anchor']=[image.width/2.,image.height/2.]
    return image,info

def proof(world, parts, color, filename):
    sheet=Image.new('RGB',(1260,760),color)
    draw=ImageDraw.Draw(sheet)
    ink='white' if sum(color)<400 else '#111820'
    for i,part in enumerate(parts):
        x,y=(i%3)*420,(i//3)*380
        thumb=part.copy(); thumb.thumbnail((380,280),Image.Resampling.LANCZOS)
        sheet.paste(thumb,(x+(420-thumb.width)//2,y+18),thumb)
        draw.text((x+16,y+306),NAMES[i],fill=ink)
        actual=part.resize(ACTUAL[world][i],Image.Resampling.LANCZOS)
        # Actual-size corner demonstrates atlas readability; not a gameplay capture.
        fit=min(1., 58/actual.height)
        if fit<1: actual=actual.resize((round(actual.width*fit),58),Image.Resampling.LANCZOS)
        sheet.paste(actual,(x+180,y+305),actual)
    sheet.save(QA/filename)

def main():
    OUTPUT.mkdir(parents=True,exist_ok=True); QA.mkdir(parents=True,exist_ok=True)
    report={'format':1,'tool':'built-in image_gen','method':'Native RGBA crop bounded by alpha >=8 to exclude remote near-transparent noise; no background extraction, alpha normalization, matte or connected-component removal. Uniform maximum edge640; two-pixel transparent guard; immutable originals. Actor frames pre-minified by AssetStore at load.', 'worlds':{}}
    for world in (3,4,5):
        actor_path=SOURCES/f'chapter{world}-actors-generated.png'
        bg_path=SOURCES/f'chapter{world}-background-generated.png'
        actor=Image.open(actor_path); bg=Image.open(bg_path)
        assert actor.mode=='RGBA' and actor.size==(1536,1024)
        assert bg.mode=='RGB' and bg.size==(1774,887)
        sources={p.name:sha(p) for p in (actor_path,bg_path)}
        bg_name=f'chapter{world}-background'
        shutil.copyfile(bg_path,OUTPUT/(bg_name+'.png'))
        (OUTPUT/(bg_name+'.properties')).write_text(metadata(bg_name,[{'name':'backdrop','atlas_rect':[0,0,*bg.size],'anchor':[0,0]}],0),encoding='utf-8')
        parts=[]; infos=[]
        for cell,name,sockets in zip(CELLS[world],NAMES,SOCKETS[world]):
            part,info=prepare(actor,cell,name,sockets); parts.append(part); infos.append(info)
        atlas=Image.new('RGBA',(sum(p.width+4 for p in parts)+4,max(p.height for p in parts)+8))
        x=4
        for part,info in zip(parts,infos):
            atlas.paste(part,(x,4)); info['atlas_rect']=[x,4,*part.size]; x+=part.width+4
        actor_name=f'chapter{world}-actors'
        atlas.save(OUTPUT/(actor_name+'.png'),optimize=True)
        (OUTPUT/(actor_name+'.properties')).write_text(metadata(actor_name,infos,20),encoding='utf-8')
        for label,color in [('black',(8,12,19)),('white',(246,246,238)),('blue',(49,92,119))]:
            proof(world,parts,color,f'chapter{world}-{label}.png')
        bg.resize((960,480),Image.Resampling.LANCZOS).save(QA/f'chapter{world}-background-960.png')
        outputs={p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in OUTPUT.glob(f'chapter{world}-*')}
        report['worlds'][world]={'source_sha256':sources,'actor_source_size':list(actor.size),'background_source_size':list(bg.size),'parts':infos,'outputs':outputs}
        assert all(sha(SOURCES/name)==digest for name,digest in sources.items())
    report['export_script_sha256']=sha(Path(__file__))
    (ROOT/'docs/design/evolution/chapter-art-provenance.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({world: {'parts':len(value['parts']),'outputs':value['outputs']} for world,value in report['worlds'].items()},indent=2))

if __name__=='__main__': main()
