# Native-alpha generated rig; export_characters.py
format=1
atlas=game/art/engineer.png
pixelsPerUnit=1
layer=20
default=head
clips=head,torso,upper-arm,forearm,thigh,shin,cannon,scarf

clip.head.loop=true
clip.head.frames=head
frame.head.rect=4,4,348,329
frame.head.durationMs=1000
frame.head.anchor=174.00,164.50
frame.head.sockets=neck
frame.head.socket.neck=151.00,298.00

clip.torso.loop=true
clip.torso.frames=torso
frame.torso.rect=500,4,309,427
frame.torso.durationMs=1000
frame.torso.anchor=154.50,213.50
frame.torso.sockets=neck,shoulder,hip
frame.torso.socket.neck=168.00,45.00
frame.torso.socket.shoulder=36.00,116.00
frame.torso.socket.hip=155.00,378.00

clip.upper-arm.loop=true
clip.upper-arm.frames=upper-arm
frame.upper-arm.rect=996,4,161,352
frame.upper-arm.durationMs=1000
frame.upper-arm.anchor=74.00,42.00
frame.upper-arm.sockets=distal
frame.upper-arm.socket.distal=65.00,320.00

clip.forearm.loop=true
clip.forearm.frames=forearm
frame.forearm.rect=1492,4,186,356
frame.forearm.durationMs=1000
frame.forearm.anchor=48.00,68.00
frame.forearm.sockets=distal,wrist
frame.forearm.socket.distal=127.00,298.00
frame.forearm.socket.wrist=86.00,240.00

clip.thigh.loop=true
clip.thigh.frames=thigh
frame.thigh.rect=4,439,194,383
frame.thigh.durationMs=1000
frame.thigh.anchor=98.00,38.00
frame.thigh.sockets=distal
frame.thigh.socket.distal=113.00,340.00

clip.shin.loop=true
clip.shin.frames=shin
frame.shin.rect=500,439,233,409
frame.shin.durationMs=1000
frame.shin.anchor=103.00,26.00
frame.shin.sockets=ankle,distal,heel,toe
frame.shin.socket.ankle=78.00,299.00
frame.shin.socket.distal=128.15,400.82
frame.shin.socket.heel=18.64,404.91
frame.shin.socket.toe=219.02,404.91

clip.cannon.loop=true
clip.cannon.frames=cannon
frame.cannon.rect=996,439,488,255
frame.cannon.durationMs=1000
frame.cannon.anchor=473.36,94.35
frame.cannon.sockets=muzzle,grip,support-grip
frame.cannon.socket.muzzle=482.00,105.00
frame.cannon.socket.grip=145.00,196.00
frame.cannon.socket.support-grip=323.00,143.00

clip.scarf.loop=true
clip.scarf.frames=scarf
frame.scarf.rect=1492,439,396,194
frame.scarf.durationMs=1000
frame.scarf.anchor=344.52,44.62
frame.scarf.sockets=tail
frame.scarf.socket.tail=31.68,126.10
