# Generated native-alpha art; export_route_props.py
format=1
atlas=game/art/route-props.png
pixelsPerUnit=1
layer=10
default=city-wall
clips=city-wall,drain-wall,gantry-wall,foundry-wall,hive-wall,walkway,console,nerve-console

clip.city-wall.loop=true
clip.city-wall.frames=city-wall
frame.city-wall.rect=4,4,339,439
frame.city-wall.durationMs=1000
frame.city-wall.anchor=0,0

clip.drain-wall.loop=true
clip.drain-wall.frames=drain-wall
frame.drain-wall.rect=505,4,361,423
frame.drain-wall.durationMs=1000
frame.drain-wall.anchor=0,0

clip.gantry-wall.loop=true
clip.gantry-wall.frames=gantry-wall
frame.gantry-wall.rect=1006,4,368,427
frame.gantry-wall.durationMs=1000
frame.gantry-wall.anchor=0,0

clip.foundry-wall.loop=true
clip.foundry-wall.frames=foundry-wall
frame.foundry-wall.rect=1507,4,349,460
frame.foundry-wall.durationMs=1000
frame.foundry-wall.anchor=0,0

clip.hive-wall.loop=true
clip.hive-wall.frames=hive-wall
frame.hive-wall.rect=4,472,355,454
frame.hive-wall.durationMs=1000
frame.hive-wall.anchor=0,0

clip.walkway.loop=true
clip.walkway.frames=walkway
frame.walkway.rect=505,472,493,143
frame.walkway.durationMs=1000
frame.walkway.anchor=0,0

clip.console.loop=true
clip.console.frames=console
frame.console.rect=1006,472,276,353
frame.console.durationMs=1000
frame.console.anchor=0,0

clip.nerve-console.loop=true
clip.nerve-console.frames=nerve-console
frame.nerve-console.rect=1507,472,319,454
frame.nerve-console.durationMs=1000
frame.nerve-console.anchor=0,0
