# Native-alpha generated rig; export_characters.py
format=1
atlas=game/art/scout.png
pixelsPerUnit=1
layer=20
default=head
clips=head,torso,upper-arm,forearm,thigh,shin,cannon,scarf

clip.head.loop=true
clip.head.frames=head
frame.head.rect=4,4,283,392
frame.head.durationMs=1000
frame.head.anchor=141.50,196.00
frame.head.sockets=neck
frame.head.socket.neck=123.00,292.00

clip.torso.loop=true
clip.torso.frames=torso
frame.torso.rect=450,4,257,412
frame.torso.durationMs=1000
frame.torso.anchor=128.50,206.00
frame.torso.sockets=neck,shoulder,hip
frame.torso.socket.neck=143.00,64.00
frame.torso.socket.shoulder=45.00,111.00
frame.torso.socket.hip=123.00,349.00

clip.upper-arm.loop=true
clip.upper-arm.frames=upper-arm
frame.upper-arm.rect=896,4,142,419
frame.upper-arm.durationMs=1000
frame.upper-arm.anchor=30.00,70.00
frame.upper-arm.sockets=distal
frame.upper-arm.socket.distal=64.00,350.00

clip.forearm.loop=true
clip.forearm.frames=forearm
frame.forearm.rect=1342,4,110,424
frame.forearm.durationMs=1000
frame.forearm.anchor=35.00,56.00
frame.forearm.sockets=distal
frame.forearm.socket.distal=45.00,332.00

clip.thigh.loop=true
clip.thigh.frames=thigh
frame.thigh.rect=4,439,184,427
frame.thigh.durationMs=1000
frame.thigh.anchor=36.00,58.00
frame.thigh.sockets=distal
frame.thigh.socket.distal=82.00,361.00

clip.shin.loop=true
clip.shin.frames=shin
frame.shin.rect=450,439,251,427
frame.shin.durationMs=1000
frame.shin.anchor=53.00,40.00
frame.shin.sockets=ankle,distal,heel,toe
frame.shin.socket.ankle=54.00,298.00
frame.shin.socket.distal=138.05,418.46
frame.shin.socket.heel=20.08,422.73
frame.shin.socket.toe=235.94,422.73

clip.cannon.loop=true
clip.cannon.frames=cannon
frame.cannon.rect=896,439,438,218
frame.cannon.durationMs=1000
frame.cannon.anchor=424.86,80.66
frame.cannon.sockets=muzzle,grip,support-grip
frame.cannon.socket.muzzle=429.00,80.00
frame.cannon.socket.grip=121.00,158.00
frame.cannon.socket.support-grip=295.00,113.00

clip.scarf.loop=true
clip.scarf.frames=scarf
frame.scarf.rect=1342,439,383,194
frame.scarf.durationMs=1000
frame.scarf.anchor=333.21,44.62
frame.scarf.sockets=tail
frame.scarf.socket.tail=30.64,126.10
