# Native-alpha generated rig; export_characters.py
format=1
atlas=game/art/warden.png
pixelsPerUnit=1
layer=20
default=head
clips=head,torso,upper-arm,forearm,thigh,shin,cannon,scarf

clip.head.loop=true
clip.head.frames=head
frame.head.rect=4,4,329,379
frame.head.durationMs=1000
frame.head.anchor=164.50,189.50
frame.head.sockets=neck
frame.head.socket.neck=132.00,274.00

clip.torso.loop=true
clip.torso.frames=torso
frame.torso.rect=578,4,395,429
frame.torso.durationMs=1000
frame.torso.anchor=197.50,214.50
frame.torso.sockets=neck,shoulder,hip
frame.torso.socket.neck=220.00,65.00
frame.torso.socket.shoulder=57.00,121.00
frame.torso.socket.hip=188.00,369.00

clip.upper-arm.loop=true
clip.upper-arm.frames=upper-arm
frame.upper-arm.rect=1152,4,185,425
frame.upper-arm.durationMs=1000
frame.upper-arm.anchor=31.00,86.00
frame.upper-arm.sockets=distal
frame.upper-arm.socket.distal=100.00,368.00

clip.forearm.loop=true
clip.forearm.frames=forearm
frame.forearm.rect=1726,4,157,435
frame.forearm.durationMs=1000
frame.forearm.anchor=40.00,49.00
frame.forearm.sockets=distal
frame.forearm.socket.distal=69.00,340.00

clip.thigh.loop=true
clip.thigh.frames=thigh
frame.thigh.rect=4,447,208,427
frame.thigh.durationMs=1000
frame.thigh.anchor=44.00,61.00
frame.thigh.sockets=distal
frame.thigh.socket.distal=64.00,356.00

clip.shin.loop=true
clip.shin.frames=shin
frame.shin.rect=578,447,295,424
frame.shin.durationMs=1000
frame.shin.anchor=51.00,56.00
frame.shin.sockets=ankle,distal,heel,toe
frame.shin.socket.ankle=62.00,297.00
frame.shin.socket.distal=162.25,415.52
frame.shin.socket.heel=23.60,419.76
frame.shin.socket.toe=277.30,419.76

clip.cannon.loop=true
clip.cannon.frames=cannon
frame.cannon.rect=1152,447,566,254
frame.cannon.durationMs=1000
frame.cannon.anchor=549.02,93.98
frame.cannon.sockets=muzzle,grip,support-grip
frame.cannon.socket.muzzle=558.00,116.00
frame.cannon.socket.grip=96.00,191.00
frame.cannon.socket.support-grip=368.00,160.00

clip.scarf.loop=true
clip.scarf.frames=scarf
frame.scarf.rect=1726,447,312,254
frame.scarf.durationMs=1000
frame.scarf.anchor=271.44,58.42
frame.scarf.sockets=tail
frame.scarf.socket.tail=24.96,165.10
