package com.bigphil.mergehell;

public enum GameState {
    MENU, BRIEFING, RUNNING, BOSS_WARNING, BOSS_FIGHT, LEVEL_CLEAR,
    UPGRADE_SELECTION, MISSION_COMPLETE, GAME_OVER, VICTORY, PAUSED, ERROR
}
